// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TvCinema.MovieApi.Service.Infrastructure.Context;

#nullable disable

namespace TvCinema.MovieApi.Service.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TvCinema.MovieApi.Service.Domain.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Awards")
                        .HasColumnType("text");

                    b.Property<string>("CodeStars")
                        .HasColumnType("text");

                    b.Property<string>("Companies")
                        .HasColumnType("text");

                    b.Property<string>("Countries")
                        .HasColumnType("text");

                    b.Property<string>("DateFile")
                        .HasColumnType("text");

                    b.Property<string>("Directors")
                        .HasColumnType("text");

                    b.Property<bool>("ExistFile")
                        .HasColumnType("boolean");

                    b.Property<string>("Extension")
                        .HasColumnType("text");

                    b.Property<bool>("Favorite")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstGenre")
                        .HasColumnType("text");

                    b.Property<string>("Franchise")
                        .HasColumnType("text");

                    b.Property<string>("FullTitle")
                        .HasColumnType("text");

                    b.Property<string>("GenrePath")
                        .HasColumnType("text");

                    b.Property<string>("Genres")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("ImdbId")
                        .HasColumnType("text");

                    b.Property<string>("ImdbRating")
                        .HasColumnType("text");

                    b.Property<string>("ImdbVotes")
                        .HasColumnType("text");

                    b.Property<string>("Languages")
                        .HasColumnType("text");

                    b.Property<int>("Lenght")
                        .HasColumnType("integer");

                    b.Property<bool>("List")
                        .HasColumnType("boolean");

                    b.Property<string>("MoviePath")
                        .HasColumnType("text");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("text");

                    b.Property<string>("Plot")
                        .HasColumnType("text");

                    b.Property<string>("PlotLocal")
                        .HasColumnType("text");

                    b.Property<string>("Poster")
                        .HasColumnType("text");

                    b.Property<string>("Rated")
                        .HasColumnType("text");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("text");

                    b.Property<string>("RootPath")
                        .HasColumnType("text");

                    b.Property<string>("RuntimeMins")
                        .HasColumnType("text");

                    b.Property<string>("RuntimeStr")
                        .HasColumnType("text");

                    b.Property<string>("Stars")
                        .HasColumnType("text");

                    b.Property<string>("SubtitlePath")
                        .HasColumnType("text");

                    b.Property<string>("Tagline")
                        .HasColumnType("text");

                    b.Property<string>("TextImdb")
                        .HasColumnType("text");

                    b.Property<string>("Theme")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<bool>("Watched")
                        .HasColumnType("boolean");

                    b.Property<string>("Writer")
                        .HasColumnType("text");

                    b.Property<string>("Year")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
